version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      # Create persistent volumes for media and model cache
      # - ml_models_data:/app/ml_models
      # - media_data:/app/media
      - ./media:/app/media
      - ./ml_models:/app/ml_models
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    restart: unless-stopped

# volumes:
#   ml_models_data:
#     # This volume persists the downloaded ML models between container restarts
#   media_data:
#     # This volume persists uploaded books and translations