version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend-network
  
  worker:
    build: .
    command: python manage.py rundramatiq
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - backend-network

volumes:
  postgresql:
  redis:

networks:
  backend-network:
    driver: bridge