# Generated by Django 5.1.7 on 2025-03-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='completed_chunks',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='total_chunks',
        ),
    ]
