# Generated by Django 5.1.7 on 2025-03-16 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_create_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountVerification',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='verification', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('verification_code', models.CharField(max_length=6, unique=True)),
                ('expiration_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'account_verification',
            },
        ),
    ]
