# Generated by Django 5.1.7 on 2025-03-16 09:27

import django.core.validators
import translator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file_format',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF'), ('epub', 'EPUB'), ('txt', 'Plain Text'), ('docx', 'Word Document'), ('html', 'HTML'), ('md', 'Markdown')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, help_text='Supported formats: PDF, EPUB, TXT, DOCX, HTML, MD (max 50MB)', null=True, upload_to='books/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'epub', 'txt', 'docx', 'html', 'md']), translator.models.validate_book_file]),
        ),
    ]
